network:
  interface: "eth0"
  dhcp_range_start: "192.168.100.100"
  dhcp_range_end: "192.168.100.200"
  subnet_mask: "255.255.255.0"
  gateway: "192.168.100.10"

dhcp:
  config_file: "/etc/dnsmasq.d/ipmirage.conf"
  leases_file: "/var/lib/misc/dnsmasq.leases"

ipmi:
  username: "ADMIN"
  password: "ADMIN"
